"""mitre attack catalog

Revision ID: 195ced470091
Revises: 537e1a8b02b0
Create Date: 2026-09-13 11:14:04.297583

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '195ced470091'
down_revision: str | None = '537e1a8b02b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitre_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('attack_version', sa.String(length=32), nullable=True),
    sa.Column('spec_version', sa.String(length=32), nullable=True),
    sa.Column('tactics_imported', sa.Integer(), nullable=False),
    sa.Column('techniques_imported', sa.Integer(), nullable=False),
    sa.Column('objects_rejected', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=500), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mitre_tactics',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('shortname', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_tactics_shortname'), 'mitre_tactics', ['shortname'], unique=False)
    op.create_table('mitre_techniques',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_subtechnique', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.String(length=16), nullable=True),
    sa.Column('platforms', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('data_sources', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_by', sa.String(length=16), nullable=True),
    sa.Column('attack_version', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_techniques_parent_id'), 'mitre_techniques', ['parent_id'], unique=False)
    op.create_table('mitre_technique_tactics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('technique_id', sa.String(length=16), nullable=False),
    sa.Column('tactic_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tactic_id'], ['mitre_tactics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['mitre_techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technique_id', 'tactic_id', name='uq_technique_tactic')
    )
    op.create_table('rule_mitre_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('technique_id', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['detection_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['mitre_techniques.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'technique_id', name='uq_rule_mitre_map')
    )
    # ### end Alembic commands ###
    # (Autogenerate again proposed dropping indexes created by raw SQL in
    # earlier migrations; those drops were removed by hand.)

    # The ATT&CK catalog itself carries no tenant: it is public knowledge,
    # identical for everyone, and duplicating 858 techniques per tenant
    # would buy nothing. Only the rule↔technique mapping is tenant data.
    op.execute("ALTER TABLE rule_mitre_map ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE rule_mitre_map FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation_rule_mitre_map ON rule_mitre_map
        USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
        WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
        """
    )

    op.create_index("idx_rule_mitre_map_tenant", "rule_mitre_map", ["tenant_id", "technique_id"])
    op.create_index("idx_mitre_technique_tactics_tactic", "mitre_technique_tactics", ["tactic_id"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_mitre_map')
    op.drop_table('mitre_technique_tactics')
    op.drop_index(op.f('ix_mitre_techniques_parent_id'), table_name='mitre_techniques')
    op.drop_table('mitre_techniques')
    op.drop_index(op.f('ix_mitre_tactics_shortname'), table_name='mitre_tactics')
    op.drop_table('mitre_tactics')
    op.drop_table('mitre_imports')
    # ### end Alembic commands ###
