"""assets

Revision ID: 1d14eb8ce2a4
Revises: 67705d355d3b
Create Date: 2026-09-13 00:16:29.962012

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1d14eb8ce2a4'
down_revision: str | None = '67705d355d3b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('mac_address', postgresql.MACADDR(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('criticality', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_type IN ('server', 'endpoint', 'laptop', 'network_device', 'cloud_resource', 'application')", name='ck_assets_type'),
    sa.CheckConstraint("criticality IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='ck_assets_criticality'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Tenant isolation, same pattern as every other tenant-scoped table
    # (THREAT_MODEL.md §3.2): enabled AND forced, so it applies to the
    # table-owning application role too, with a fail-closed policy that
    # returns nothing when no tenant context is set.
    op.execute("ALTER TABLE assets ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE assets FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation_assets ON assets
        USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
        """
    )
    op.create_index("idx_assets_tenant_hostname", "assets", ["tenant_id", "hostname"])
    op.create_index("idx_assets_tenant_ip", "assets", ["tenant_id", "ip_address"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    # ### end Alembic commands ###
