"""playbooks

Revision ID: 3f883563c607
Revises: 5a7091c56785
Create Date: 2026-09-13 22:54:41.336902

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3f883563c607'
down_revision: str | None = '5a7091c56785'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('enabled', 'disabled')", name='ck_playbooks_status'),
    sa.CheckConstraint("trigger_type IN ('manual', 'alert')", name='ck_playbooks_trigger_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playbook_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('playbook_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'AWAITING_APPROVAL', 'COMPLETED', 'FAILED', 'REJECTED')", name='ck_playbook_runs_status'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playbook_action_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('playbook_run_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('action_name', sa.String(), nullable=False),
    sa.Column('preview', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTED')", name='ck_playbook_approvals_status'),
    sa.CheckConstraint('decided_by IS NULL OR decided_by != requested_by', name='ck_playbook_action_approvals_dual_control'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['playbook_run_id'], ['playbook_runs.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assets', sa.Column('is_isolated', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('assets', 'is_isolated', server_default=None)
    op.add_column('assets', sa.Column('isolated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # (Autogenerate also proposed dropping every hand-written index across
    # the whole schema this time, not just this migration's own tables: it
    # cannot see indexes created by raw SQL in earlier migrations and diffs
    # against the full model on every run. Those drops were removed by
    # hand, as in every migration before this one that touched a table
    # with a raw-SQL index.)

    for table in ("playbooks", "playbook_runs", "playbook_action_approvals"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation_{table} ON {table}
            USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
            WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
            """
        )

    op.create_index(
        "idx_playbooks_tenant_key", "playbooks", ["tenant_id", "key"], unique=True
    )
    op.create_index(
        "idx_playbook_runs_tenant_playbook", "playbook_runs", ["tenant_id", "playbook_id"]
    )
    op.create_index(
        "idx_playbook_runs_tenant_status", "playbook_runs", ["tenant_id", "status"]
    )
    op.create_index(
        "idx_playbook_approvals_run", "playbook_action_approvals", ["playbook_run_id"]
    )
    op.create_index(
        "idx_playbook_approvals_tenant_status",
        "playbook_action_approvals",
        ["tenant_id", "status"],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'isolated_at')
    op.drop_column('assets', 'is_isolated')
    op.drop_table('playbook_action_approvals')
    op.drop_table('playbook_runs')
    op.drop_table('playbooks')
    # ### end Alembic commands ###
