"""threat intelligence

Revision ID: 537e1a8b02b0
Revises: 8bea78320bb9
Create Date: 2026-09-13 10:38:47.883638

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '537e1a8b02b0'
down_revision: str | None = '8bea78320bb9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ioc_feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('connector_type', sa.String(length=64), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credential_ref', sa.String(length=200), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_ioc_feeds_tenant_name')
    )
    op.create_table('iocs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('ioc_type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("classification IN ('malicious', 'suspicious', 'benign', 'unknown')", name='ck_iocs_classification'),
    sa.CheckConstraint("classification IN ('unknown','benign') OR length(trim(source)) > 0", name='ck_iocs_source_required'),
    sa.CheckConstraint("ioc_type IN ('ipv4', 'ipv6', 'domain', 'url', 'md5', 'sha1', 'sha256', 'email', 'asn', 'certificate')", name='ck_iocs_type'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name='ck_iocs_confidence'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'ioc_type', 'value', 'source', name='uq_iocs_identity')
    )
    op.create_table('ioc_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ioc_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('changed_field', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # (Autogenerate also proposed dropping the hand-written indexes from the
    # assets and detection-rule migrations: it cannot see indexes created by
    # raw SQL. Those drops were removed by hand.)

    # Tenant isolation, with one deliberate difference from every other
    # tenant-scoped table: a NULL tenant_id means a shared/global feed
    # indicator (app/models/threat_intel.py explains why intel is not
    # duplicated per tenant). Readable by everyone, writable by no tenant —
    # the WITH CHECK clause has no `OR tenant_id IS NULL`, so a tenant
    # session cannot create or edit a global row, only the feed sync path
    # (which runs with no tenant context, outside RLS' USING clause) can.
    for table in ("iocs", "ioc_history", "ioc_feeds"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation_{table} ON {table}
            USING (
                tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid
                OR tenant_id IS NULL
            )
            WITH CHECK (
                tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid
            )
            """
        )

    # The one writer of shared/global indicators. A tenant session can never
    # satisfy this policy's WITH CHECK (it only writes rows stamped with its
    # own tenant), and the feed sync path can only write rows with NO tenant
    # — so neither can reach the other's data. `app.intel_sync` is trusted
    # infrastructure in exactly the same way `app.current_tenant_id` is:
    # both are set by the session factory, never from request input.
    op.execute(
        """
        CREATE POLICY intel_sync_iocs ON iocs
        USING (current_setting('app.intel_sync', true) = 'on' AND tenant_id IS NULL)
        WITH CHECK (current_setting('app.intel_sync', true) = 'on' AND tenant_id IS NULL)
        """
    )
    op.execute(
        """
        CREATE POLICY intel_sync_ioc_feeds ON ioc_feeds
        USING (current_setting('app.intel_sync', true) = 'on' AND tenant_id IS NULL)
        WITH CHECK (current_setting('app.intel_sync', true) = 'on' AND tenant_id IS NULL)
        """
    )

    # Indicator history is append-only for the same reason the audit log is:
    # "who downgraded this indicator to benign the week before the breach"
    # has to be answerable, and a history someone can edit answers nothing.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION reject_ioc_history_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'ioc_history is append-only: % is not permitted', TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for operation in ("update", "delete"):
        op.execute(
            f"""
            CREATE TRIGGER ioc_history_reject_{operation}
            BEFORE {operation.upper()} ON ioc_history
            FOR EACH ROW EXECUTE FUNCTION reject_ioc_history_mutation()
            """
        )

    # The lookup path: enrichment resolves (type, value) for every event, so
    # this index is the difference between intel matching being free and
    # being the pipeline's bottleneck.
    op.create_index("idx_iocs_lookup", "iocs", ["ioc_type", "value"])
    op.create_index("idx_iocs_tenant", "iocs", ["tenant_id"])
    op.create_index("idx_iocs_expiry", "iocs", ["expires_at"])
    op.create_index("idx_ioc_history_ioc", "ioc_history", ["ioc_id"])


def downgrade() -> None:
    for operation in ("update", "delete"):
        op.execute(f"DROP TRIGGER IF EXISTS ioc_history_reject_{operation} ON ioc_history")
    op.execute("DROP FUNCTION IF EXISTS reject_ioc_history_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ioc_history')
    op.drop_table('iocs')
    op.drop_table('ioc_feeds')
    # ### end Alembic commands ###
