"""saved hunts

Revision ID: 5a7091c56785
Revises: 7d304880a756
Create Date: 2026-09-13 16:10:42.774430

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5a7091c56785'
down_revision: str | None = '7d304880a756'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_hunts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # (Autogenerate also proposed dropping every hand-written index across
    # the whole schema this time, not just this migration's own table: it
    # cannot see indexes created by raw SQL in earlier migrations and diffs
    # against the full model on every run. Those drops were removed by hand,
    # as in every migration before this one that touched a table with a
    # raw-SQL index.)

    op.execute("ALTER TABLE saved_hunts ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE saved_hunts FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation_saved_hunts ON saved_hunts
        USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
        WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
        """
    )
    op.create_index("idx_saved_hunts_tenant", "saved_hunts", ["tenant_id", "created_at"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_hunts')
    # ### end Alembic commands ###
