"""incidents

Revision ID: 7d304880a756
Revises: b1c551ce52bd
Create Date: 2026-09-13 12:46:01.665937

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7d304880a756'
down_revision: str | None = 'b1c551ce52bd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_sequences',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'year')
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('display_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('analyst_id', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('P1', 'P2', 'P3', 'P4')", name='ck_incidents_priority'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_incidents_severity'),
    sa.CheckConstraint("status IN ('NEW', 'TRIAGE', 'INVESTIGATION', 'CONTAINMENT', 'ERADICATION', 'RECOVERY', 'CLOSED')", name='ck_incidents_status'),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'display_id', name='uq_incidents_display_id')
    )
    op.create_table('incident_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'alert_id', name='uq_incident_alert')
    )
    op.create_table('incident_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'asset_id', name='uq_incident_asset')
    )
    op.create_table('incident_iocs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('ioc_id', sa.UUID(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'ioc_id', name='uq_incident_ioc')
    )
    op.create_table('incident_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'done')", name='ck_incident_tasks_status'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_timeline',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.CheckConstraint("kind IN ('status_change', 'note', 'task', 'alert_linked', 'asset_linked', 'ioc_linked', 'assignment', 'created')", name='ck_incident_timeline_kind'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=300), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'username', name='uq_incident_user')
    )
    # ### end Alembic commands ###
    # (Autogenerate proposed dropping indexes created by raw SQL in earlier
    # migrations; those drops were removed by hand.)

    incident_tables = (
        "incidents",
        "incident_alerts",
        "incident_assets",
        "incident_iocs",
        "incident_users",
        "incident_notes",
        "incident_tasks",
        "incident_timeline",
        "incident_sequences",
    )
    for table in incident_tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation_{table} ON {table}
            USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
            WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
            """
        )

    # The incident record exists for two things — handing the case to the
    # next shift, and explaining afterwards what was known and when. Both
    # depend on the history being unrewritable, so the database enforces it
    # rather than the service layer.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION reject_incident_history_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only: % is not permitted', TG_TABLE_NAME, TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table in ("incident_timeline", "incident_notes"):
        for operation in ("update", "delete"):
            op.execute(
                f"""
                CREATE TRIGGER {table}_reject_{operation}
                BEFORE {operation.upper()} ON {table}
                FOR EACH ROW EXECUTE FUNCTION reject_incident_history_mutation()
                """
            )

    op.create_index("idx_incidents_tenant_status", "incidents", ["tenant_id", "status"])
    op.create_index("idx_incident_timeline_incident", "incident_timeline", ["incident_id"])
    op.create_index("idx_incident_tasks_incident", "incident_tasks", ["incident_id"])
    op.create_index("idx_incident_alerts_alert", "incident_alerts", ["alert_id"])


def downgrade() -> None:
    for table in ("incident_timeline", "incident_notes"):
        for operation in ("update", "delete"):
            op.execute(f"DROP TRIGGER IF EXISTS {table}_reject_{operation} ON {table}")
    op.execute("DROP FUNCTION IF EXISTS reject_incident_history_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_users')
    op.drop_table('incident_timeline')
    op.drop_table('incident_tasks')
    op.drop_table('incident_notes')
    op.drop_table('incident_iocs')
    op.drop_table('incident_assets')
    op.drop_table('incident_alerts')
    op.drop_table('incidents')
    op.drop_table('incident_sequences')
    # ### end Alembic commands ###
