"""detection rules

Revision ID: 8bea78320bb9
Revises: 1d14eb8ce2a4
Create Date: 2026-09-13 07:02:18.085995

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8bea78320bb9'
down_revision: str | None = '1d14eb8ce2a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), nullable=False),
    sa.Column('risk_score', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('definition_yaml', sa.Text(), nullable=False),
    sa.Column('false_positive_notes', sa.Text(), nullable=True),
    sa.Column('investigation_steps', sa.Text(), nullable=True),
    sa.Column('references_urls', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('mitre_techniques', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rule_type IN ('streaming', 'windowed')", name='ck_detection_rules_type'),
    sa.CheckConstraint("severity IN ('informational', 'low', 'medium', 'high', 'critical')", name='ck_detection_rules_severity'),
    sa.CheckConstraint("status IN ('enabled', 'disabled', 'testing')", name='ck_detection_rules_status'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name='ck_detection_rules_confidence'),
    sa.CheckConstraint('risk_score BETWEEN 0 AND 100', name='ck_detection_rules_risk'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'rule_key', name='uq_detection_rules_tenant_key')
    )
    op.create_table('detection_rule_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition_yaml', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['detection_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version', name='uq_detection_rule_versions_rule_version')
    )
    op.create_table('rule_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('match_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['detection_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # (Autogenerate proposed dropping idx_assets_tenant_hostname /
    # idx_assets_tenant_ip here: it does not know about indexes created by
    # raw SQL in an earlier migration. Those drops were removed by hand —
    # never let autogenerate delete something it merely cannot see.)

    # Tenant isolation, same pattern as every other tenant-scoped table
    # (THREAT_MODEL.md §3.2): enabled AND forced, fail-closed when no tenant
    # context is set. WITH CHECK is spelled out on the rule tables because a
    # policy with only USING would let a tenant *write* a row stamped with
    # someone else's tenant_id even though it could never read it back.
    for table in ("detection_rules", "detection_rule_versions", "rule_exceptions"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation_{table} ON {table}
            USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
            WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
            """
        )

    # Rule history is append-only for the same reason the audit log is: a
    # detection that was weakened before an incident must still be provable
    # afterwards, and a history someone can edit proves nothing. Enforced by
    # the database, not by convention in the service layer.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION reject_rule_version_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'detection_rule_versions is append-only: % is not permitted', TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER detection_rule_versions_reject_update
        BEFORE UPDATE ON detection_rule_versions
        FOR EACH ROW EXECUTE FUNCTION reject_rule_version_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER detection_rule_versions_reject_delete
        BEFORE DELETE ON detection_rule_versions
        FOR EACH ROW EXECUTE FUNCTION reject_rule_version_mutation()
        """
    )

    op.create_index(
        "idx_detection_rules_tenant_status", "detection_rules", ["tenant_id", "status"]
    )
    op.create_index(
        "idx_detection_rules_tenant_type", "detection_rules", ["tenant_id", "rule_type"]
    )
    op.create_index("idx_rule_exceptions_rule", "rule_exceptions", ["rule_id"])


def downgrade() -> None:
    op.execute(
        "DROP TRIGGER IF EXISTS detection_rule_versions_reject_delete "
        "ON detection_rule_versions"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS detection_rule_versions_reject_update "
        "ON detection_rule_versions"
    )
    op.execute("DROP FUNCTION IF EXISTS reject_rule_version_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_exceptions')
    op.drop_table('detection_rule_versions')
    op.drop_table('detection_rules')
    # ### end Alembic commands ###
