"""alerts

Revision ID: b1c551ce52bd
Revises: 195ced470091
Create Date: 2026-09-13 11:42:33.517646

"""
import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b1c551ce52bd'
down_revision: str | None = '195ced470091'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Frozen snapshot of what THIS migration adds to the RBAC catalog (seed data
# is never imported from live application code — see the initial RBAC
# migration). `alert:close` is what makes the L1/L2 tier distinction real:
# an L1 can triage and escalate, only L2 and above can decide an alert is
# over (spec §13's analyst tiers).
_NEW_PERMISSIONS = (("alert", "close"),)

_NEW_GRANTS = (
    "SUPER_ADMIN",
    "ORG_ADMIN",
    "SOC_MANAGER",
    "SOC_ANALYST_L2",
    "SOC_ANALYST_L3",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_sequences',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'year')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('display_id', sa.String(length=32), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), nullable=False),
    sa.Column('risk_score', sa.SmallInteger(), nullable=False),
    sa.Column('risk_bucket', sa.String(length=16), nullable=True),
    sa.Column('risk_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('detection_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_user', sa.String(length=300), nullable=True),
    sa.Column('affected_host', sa.String(length=300), nullable=True),
    sa.Column('source_ip', postgresql.INET(), nullable=True),
    sa.Column('destination_ip', postgresql.INET(), nullable=True),
    sa.Column('mitre_techniques', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('analyst_id', sa.UUID(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('dedup_key', sa.String(length=500), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('informational', 'low', 'medium', 'high', 'critical')", name='ck_alerts_severity'),
    sa.CheckConstraint("status IN ('NEW', 'IN_PROGRESS', 'ESCALATED', 'FALSE_POSITIVE', 'RESOLVED', 'CLOSED')", name='ck_alerts_status'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name='ck_alerts_confidence'),
    sa.CheckConstraint('occurrence_count >= 1', name='ck_alerts_occurrences'),
    sa.CheckConstraint('risk_score BETWEEN 0 AND 100', name='ck_alerts_risk'),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['detection_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # (Autogenerate proposed dropping indexes created by raw SQL in earlier
    # migrations; those drops were removed by hand.)

    for table in ("alerts", "alert_notes", "alert_transitions", "alert_sequences"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation_{table} ON {table}
            USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
            WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)
            """
        )

    # An alert's history is evidence about the analysts, not just about the
    # attack: "who called this a false positive, and when" is the first
    # question after a missed incident, and a history that can be edited
    # answers nothing. Enforced by the database, like the audit log.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION reject_alert_history_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only: % is not permitted', TG_TABLE_NAME, TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table in ("alert_notes", "alert_transitions"):
        for operation in ("update", "delete"):
            op.execute(
                f"""
                CREATE TRIGGER {table}_reject_{operation}
                BEFORE {operation.upper()} ON {table}
                FOR EACH ROW EXECUTE FUNCTION reject_alert_history_mutation()
                """
            )

    op.create_index("idx_alerts_tenant_status", "alerts", ["tenant_id", "status"])
    op.create_index("idx_alerts_dedup", "alerts", ["tenant_id", "dedup_key", "last_seen_at"])
    op.create_index("idx_alerts_tenant_display", "alerts", ["tenant_id", "display_id"], unique=True)
    op.create_index("idx_alert_notes_alert", "alert_notes", ["alert_id"])
    op.create_index("idx_alert_transitions_alert", "alert_transitions", ["alert_id"])

    # --- RBAC: the alert:close permission ---
    connection = op.get_bind()
    permission_id = uuid.uuid4()
    connection.execute(
        sa.text("INSERT INTO permissions (id, resource, action) VALUES (:id, 'alert', 'close')"),
        {"id": permission_id},
    )
    for role_name in _NEW_GRANTS:
        role_id = connection.execute(
            sa.text("SELECT id FROM roles WHERE name = :name"), {"name": role_name}
        ).scalar_one()
        connection.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_id) "
                "VALUES (:role_id, :permission_id)"
            ),
            {"role_id": role_id, "permission_id": permission_id},
        )


def downgrade() -> None:
    connection = op.get_bind()
    connection.execute(
        sa.text(
            "DELETE FROM role_permissions WHERE permission_id IN "
            "(SELECT id FROM permissions WHERE resource = 'alert' AND action = 'close')"
        )
    )
    connection.execute(
        sa.text("DELETE FROM permissions WHERE resource = 'alert' AND action = 'close'")
    )
    for table in ("alert_notes", "alert_transitions"):
        for operation in ("update", "delete"):
            op.execute(f"DROP TRIGGER IF EXISTS {table}_reject_{operation} ON {table}")
    op.execute("DROP FUNCTION IF EXISTS reject_alert_history_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_transitions')
    op.drop_table('alert_notes')
    op.drop_table('alerts')
    op.drop_table('alert_sequences')
    # ### end Alembic commands ###
